# Generated by Django 5.2.1 on 2025-05-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Balance',
            field=models.IntegerField(default=1000, verbose_name='残高'),
        ),
    ]
